name: Generate JupyMD Download Badge

on:
  schedule:
    - cron: "0 */6 * * *" # run every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Show current directory and list files
        run: |
            pwd
            ls -R

      - name: Generate badge
        run: python badges/jupymd.py

      - name: Commit and push badge
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add badges/download-badge.json
          git commit -m "Update download badge" || echo "No changes to commit"
          git push
